# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dawnmud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dawnmud.proto',
  package='DawnMud',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rdawnmud.proto\x12\x07\x44\x61wnMud\"\xa0\x04\n\x04Zone\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x62uilders\x18\x02 \x03(\t\x12\x10\n\x08lifespan\x18\x03 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0b\n\x03\x62ot\x18\x05 \x01(\x05\x12\x0b\n\x03top\x18\x06 \x01(\x05\x12+\n\nreset_mode\x18\x07 \x01(\x0e\x32\x17.DawnMud.Zone.ResetMode\x12\x0e\n\x06number\x18\x08 \x01(\x05\x12.\n\treset_com\x18\t \x01(\x0b\x32\x1b.DawnMud.Zone.ResetCommands\x1a\x9b\x02\n\rResetCommands\x12\x35\n\x07\x63ommand\x18\x01 \x01(\x0e\x32$.DawnMud.Zone.ResetCommands.Commands\x12\x0f\n\x07if_flag\x18\x02 \x01(\x08\x12\x0c\n\x04\x61rg1\x18\x03 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x04 \x01(\x05\x12\x0c\n\x04\x61rg3\x18\x05 \x01(\x05\x12\x0c\n\x04line\x18\x06 \x01(\x05\"\x89\x01\n\x08\x43ommands\x12\x0f\n\x0bREAD_MOBILE\x10\x00\x12\x0f\n\x0bREAD_OBJECT\x10\x01\x12\x10\n\x0cGIVE_OBJ_MOB\x10\x02\x12\x0f\n\x0bPUT_OBJ_OBJ\x10\x03\x12\x11\n\rGIVE_OBJ_CHAR\x10\x04\x12\x12\n\x0eOBJ_CHAR_EQUIP\x10\x05\x12\x11\n\rSTATE_OF_DOOR\x10\x06\"4\n\tResetMode\x12\x0c\n\x08NO_RESET\x10\x00\x12\t\n\x05RESET\x10\x01\x12\x0e\n\nHARD_RESET\x10\x02\"\'\n\x08ZoneList\x12\x1b\n\x04zone\x18\x01 \x03(\x0b\x32\r.DawnMud.Zoneb\x06proto3')
)



_ZONE_RESETCOMMANDS_COMMANDS = _descriptor.EnumDescriptor(
  name='Commands',
  full_name='DawnMud.Zone.ResetCommands.Commands',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READ_MOBILE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READ_OBJECT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIVE_OBJ_MOB', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUT_OBJ_OBJ', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GIVE_OBJ_CHAR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBJ_CHAR_EQUIP', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_OF_DOOR', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=380,
  serialized_end=517,
)
_sym_db.RegisterEnumDescriptor(_ZONE_RESETCOMMANDS_COMMANDS)

_ZONE_RESETMODE = _descriptor.EnumDescriptor(
  name='ResetMode',
  full_name='DawnMud.Zone.ResetMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_RESET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARD_RESET', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=519,
  serialized_end=571,
)
_sym_db.RegisterEnumDescriptor(_ZONE_RESETMODE)


_ZONE_RESETCOMMANDS = _descriptor.Descriptor(
  name='ResetCommands',
  full_name='DawnMud.Zone.ResetCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='DawnMud.Zone.ResetCommands.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='if_flag', full_name='DawnMud.Zone.ResetCommands.if_flag', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg1', full_name='DawnMud.Zone.ResetCommands.arg1', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg2', full_name='DawnMud.Zone.ResetCommands.arg2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg3', full_name='DawnMud.Zone.ResetCommands.arg3', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line', full_name='DawnMud.Zone.ResetCommands.line', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ZONE_RESETCOMMANDS_COMMANDS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=517,
)

_ZONE = _descriptor.Descriptor(
  name='Zone',
  full_name='DawnMud.Zone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DawnMud.Zone.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='builders', full_name='DawnMud.Zone.builders', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lifespan', full_name='DawnMud.Zone.lifespan', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='DawnMud.Zone.age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bot', full_name='DawnMud.Zone.bot', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='DawnMud.Zone.top', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset_mode', full_name='DawnMud.Zone.reset_mode', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='DawnMud.Zone.number', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset_com', full_name='DawnMud.Zone.reset_com', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ZONE_RESETCOMMANDS, ],
  enum_types=[
    _ZONE_RESETMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=571,
)


_ZONELIST = _descriptor.Descriptor(
  name='ZoneList',
  full_name='DawnMud.ZoneList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone', full_name='DawnMud.ZoneList.zone', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=612,
)

_ZONE_RESETCOMMANDS.fields_by_name['command'].enum_type = _ZONE_RESETCOMMANDS_COMMANDS
_ZONE_RESETCOMMANDS.containing_type = _ZONE
_ZONE_RESETCOMMANDS_COMMANDS.containing_type = _ZONE_RESETCOMMANDS
_ZONE.fields_by_name['reset_mode'].enum_type = _ZONE_RESETMODE
_ZONE.fields_by_name['reset_com'].message_type = _ZONE_RESETCOMMANDS
_ZONE_RESETMODE.containing_type = _ZONE
_ZONELIST.fields_by_name['zone'].message_type = _ZONE
DESCRIPTOR.message_types_by_name['Zone'] = _ZONE
DESCRIPTOR.message_types_by_name['ZoneList'] = _ZONELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Zone = _reflection.GeneratedProtocolMessageType('Zone', (_message.Message,), dict(

  ResetCommands = _reflection.GeneratedProtocolMessageType('ResetCommands', (_message.Message,), dict(
    DESCRIPTOR = _ZONE_RESETCOMMANDS,
    __module__ = 'dawnmud_pb2'
    # @@protoc_insertion_point(class_scope:DawnMud.Zone.ResetCommands)
    ))
  ,
  DESCRIPTOR = _ZONE,
  __module__ = 'dawnmud_pb2'
  # @@protoc_insertion_point(class_scope:DawnMud.Zone)
  ))
_sym_db.RegisterMessage(Zone)
_sym_db.RegisterMessage(Zone.ResetCommands)

ZoneList = _reflection.GeneratedProtocolMessageType('ZoneList', (_message.Message,), dict(
  DESCRIPTOR = _ZONELIST,
  __module__ = 'dawnmud_pb2'
  # @@protoc_insertion_point(class_scope:DawnMud.ZoneList)
  ))
_sym_db.RegisterMessage(ZoneList)


# @@protoc_insertion_point(module_scope)
