// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dawnmud.proto

#ifndef PROTOBUF_dawnmud_2eproto__INCLUDED
#define PROTOBUF_dawnmud_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace DawnMud {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dawnmud_2eproto();
void protobuf_AssignDesc_dawnmud_2eproto();
void protobuf_ShutdownFile_dawnmud_2eproto();

class Zone;
class ZoneList;
class Zone_ResetCommands;

enum Zone_ResetCommands_Commands {
  Zone_ResetCommands_Commands_READ_MOBILE = 0,
  Zone_ResetCommands_Commands_READ_OBJECT = 1,
  Zone_ResetCommands_Commands_GIVE_OBJ_MOB = 2,
  Zone_ResetCommands_Commands_PUT_OBJ_OBJ = 3,
  Zone_ResetCommands_Commands_GIVE_OBJ_CHAR = 4,
  Zone_ResetCommands_Commands_OBJ_CHAR_EQUIP = 5,
  Zone_ResetCommands_Commands_STATE_OF_DOOR = 6,
  Zone_ResetCommands_Commands_Zone_ResetCommands_Commands_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Zone_ResetCommands_Commands_Zone_ResetCommands_Commands_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Zone_ResetCommands_Commands_IsValid(int value);
const Zone_ResetCommands_Commands Zone_ResetCommands_Commands_Commands_MIN = Zone_ResetCommands_Commands_READ_MOBILE;
const Zone_ResetCommands_Commands Zone_ResetCommands_Commands_Commands_MAX = Zone_ResetCommands_Commands_STATE_OF_DOOR;
const int Zone_ResetCommands_Commands_Commands_ARRAYSIZE = Zone_ResetCommands_Commands_Commands_MAX + 1;

const ::google::protobuf::EnumDescriptor* Zone_ResetCommands_Commands_descriptor();
inline const ::std::string& Zone_ResetCommands_Commands_Name(Zone_ResetCommands_Commands value) {
  return ::google::protobuf::internal::NameOfEnum(
    Zone_ResetCommands_Commands_descriptor(), value);
}
inline bool Zone_ResetCommands_Commands_Parse(
    const ::std::string& name, Zone_ResetCommands_Commands* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Zone_ResetCommands_Commands>(
    Zone_ResetCommands_Commands_descriptor(), name, value);
}
enum Zone_ResetMode {
  Zone_ResetMode_NO_RESET = 0,
  Zone_ResetMode_RESET = 1,
  Zone_ResetMode_HARD_RESET = 2,
  Zone_ResetMode_Zone_ResetMode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Zone_ResetMode_Zone_ResetMode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Zone_ResetMode_IsValid(int value);
const Zone_ResetMode Zone_ResetMode_ResetMode_MIN = Zone_ResetMode_NO_RESET;
const Zone_ResetMode Zone_ResetMode_ResetMode_MAX = Zone_ResetMode_HARD_RESET;
const int Zone_ResetMode_ResetMode_ARRAYSIZE = Zone_ResetMode_ResetMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Zone_ResetMode_descriptor();
inline const ::std::string& Zone_ResetMode_Name(Zone_ResetMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Zone_ResetMode_descriptor(), value);
}
inline bool Zone_ResetMode_Parse(
    const ::std::string& name, Zone_ResetMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Zone_ResetMode>(
    Zone_ResetMode_descriptor(), name, value);
}
// ===================================================================

class Zone_ResetCommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DawnMud.Zone.ResetCommands) */ {
 public:
  Zone_ResetCommands();
  virtual ~Zone_ResetCommands();

  Zone_ResetCommands(const Zone_ResetCommands& from);

  inline Zone_ResetCommands& operator=(const Zone_ResetCommands& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Zone_ResetCommands& default_instance();

  void Swap(Zone_ResetCommands* other);

  // implements Message ----------------------------------------------

  inline Zone_ResetCommands* New() const { return New(NULL); }

  Zone_ResetCommands* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Zone_ResetCommands& from);
  void MergeFrom(const Zone_ResetCommands& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Zone_ResetCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Zone_ResetCommands_Commands Commands;
  static const Commands READ_MOBILE =
    Zone_ResetCommands_Commands_READ_MOBILE;
  static const Commands READ_OBJECT =
    Zone_ResetCommands_Commands_READ_OBJECT;
  static const Commands GIVE_OBJ_MOB =
    Zone_ResetCommands_Commands_GIVE_OBJ_MOB;
  static const Commands PUT_OBJ_OBJ =
    Zone_ResetCommands_Commands_PUT_OBJ_OBJ;
  static const Commands GIVE_OBJ_CHAR =
    Zone_ResetCommands_Commands_GIVE_OBJ_CHAR;
  static const Commands OBJ_CHAR_EQUIP =
    Zone_ResetCommands_Commands_OBJ_CHAR_EQUIP;
  static const Commands STATE_OF_DOOR =
    Zone_ResetCommands_Commands_STATE_OF_DOOR;
  static inline bool Commands_IsValid(int value) {
    return Zone_ResetCommands_Commands_IsValid(value);
  }
  static const Commands Commands_MIN =
    Zone_ResetCommands_Commands_Commands_MIN;
  static const Commands Commands_MAX =
    Zone_ResetCommands_Commands_Commands_MAX;
  static const int Commands_ARRAYSIZE =
    Zone_ResetCommands_Commands_Commands_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Commands_descriptor() {
    return Zone_ResetCommands_Commands_descriptor();
  }
  static inline const ::std::string& Commands_Name(Commands value) {
    return Zone_ResetCommands_Commands_Name(value);
  }
  static inline bool Commands_Parse(const ::std::string& name,
      Commands* value) {
    return Zone_ResetCommands_Commands_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .DawnMud.Zone.ResetCommands.Commands command = 1;
  void clear_command();
  static const int kCommandFieldNumber = 1;
  ::DawnMud::Zone_ResetCommands_Commands command() const;
  void set_command(::DawnMud::Zone_ResetCommands_Commands value);

  // optional bool if_flag = 2;
  void clear_if_flag();
  static const int kIfFlagFieldNumber = 2;
  bool if_flag() const;
  void set_if_flag(bool value);

  // optional sint32 arg1 = 3;
  void clear_arg1();
  static const int kArg1FieldNumber = 3;
  ::google::protobuf::int32 arg1() const;
  void set_arg1(::google::protobuf::int32 value);

  // optional sint32 arg2 = 4;
  void clear_arg2();
  static const int kArg2FieldNumber = 4;
  ::google::protobuf::int32 arg2() const;
  void set_arg2(::google::protobuf::int32 value);

  // optional sint32 arg3 = 5;
  void clear_arg3();
  static const int kArg3FieldNumber = 5;
  ::google::protobuf::int32 arg3() const;
  void set_arg3(::google::protobuf::int32 value);

  // optional sint32 line = 6;
  void clear_line();
  static const int kLineFieldNumber = 6;
  ::google::protobuf::int32 line() const;
  void set_line(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DawnMud.Zone.ResetCommands)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int command_;
  bool if_flag_;
  ::google::protobuf::int32 arg1_;
  ::google::protobuf::int32 arg2_;
  ::google::protobuf::int32 arg3_;
  ::google::protobuf::int32 line_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_dawnmud_2eproto();
  friend void protobuf_AssignDesc_dawnmud_2eproto();
  friend void protobuf_ShutdownFile_dawnmud_2eproto();

  void InitAsDefaultInstance();
  static Zone_ResetCommands* default_instance_;
};
// -------------------------------------------------------------------

class Zone : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DawnMud.Zone) */ {
 public:
  Zone();
  virtual ~Zone();

  Zone(const Zone& from);

  inline Zone& operator=(const Zone& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Zone& default_instance();

  void Swap(Zone* other);

  // implements Message ----------------------------------------------

  inline Zone* New() const { return New(NULL); }

  Zone* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Zone& from);
  void MergeFrom(const Zone& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Zone* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Zone_ResetCommands ResetCommands;

  typedef Zone_ResetMode ResetMode;
  static const ResetMode NO_RESET =
    Zone_ResetMode_NO_RESET;
  static const ResetMode RESET =
    Zone_ResetMode_RESET;
  static const ResetMode HARD_RESET =
    Zone_ResetMode_HARD_RESET;
  static inline bool ResetMode_IsValid(int value) {
    return Zone_ResetMode_IsValid(value);
  }
  static const ResetMode ResetMode_MIN =
    Zone_ResetMode_ResetMode_MIN;
  static const ResetMode ResetMode_MAX =
    Zone_ResetMode_ResetMode_MAX;
  static const int ResetMode_ARRAYSIZE =
    Zone_ResetMode_ResetMode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ResetMode_descriptor() {
    return Zone_ResetMode_descriptor();
  }
  static inline const ::std::string& ResetMode_Name(ResetMode value) {
    return Zone_ResetMode_Name(value);
  }
  static inline bool ResetMode_Parse(const ::std::string& name,
      ResetMode* value) {
    return Zone_ResetMode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // repeated string builders = 2;
  int builders_size() const;
  void clear_builders();
  static const int kBuildersFieldNumber = 2;
  const ::std::string& builders(int index) const;
  ::std::string* mutable_builders(int index);
  void set_builders(int index, const ::std::string& value);
  void set_builders(int index, const char* value);
  void set_builders(int index, const char* value, size_t size);
  ::std::string* add_builders();
  void add_builders(const ::std::string& value);
  void add_builders(const char* value);
  void add_builders(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& builders() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_builders();

  // optional sint32 lifespan = 3;
  void clear_lifespan();
  static const int kLifespanFieldNumber = 3;
  ::google::protobuf::int32 lifespan() const;
  void set_lifespan(::google::protobuf::int32 value);

  // optional sint32 age = 4;
  void clear_age();
  static const int kAgeFieldNumber = 4;
  ::google::protobuf::int32 age() const;
  void set_age(::google::protobuf::int32 value);

  // optional sint32 bot = 5;
  void clear_bot();
  static const int kBotFieldNumber = 5;
  ::google::protobuf::int32 bot() const;
  void set_bot(::google::protobuf::int32 value);

  // optional sint32 top = 6;
  void clear_top();
  static const int kTopFieldNumber = 6;
  ::google::protobuf::int32 top() const;
  void set_top(::google::protobuf::int32 value);

  // optional .DawnMud.Zone.ResetMode reset_mode = 7;
  void clear_reset_mode();
  static const int kResetModeFieldNumber = 7;
  ::DawnMud::Zone_ResetMode reset_mode() const;
  void set_reset_mode(::DawnMud::Zone_ResetMode value);

  // optional sint32 number = 8;
  void clear_number();
  static const int kNumberFieldNumber = 8;
  ::google::protobuf::int32 number() const;
  void set_number(::google::protobuf::int32 value);

  // repeated .DawnMud.Zone.ResetCommands reset_com = 9;
  int reset_com_size() const;
  void clear_reset_com();
  static const int kResetComFieldNumber = 9;
  const ::DawnMud::Zone_ResetCommands& reset_com(int index) const;
  ::DawnMud::Zone_ResetCommands* mutable_reset_com(int index);
  ::DawnMud::Zone_ResetCommands* add_reset_com();
  ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone_ResetCommands >*
      mutable_reset_com();
  const ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone_ResetCommands >&
      reset_com() const;

  // @@protoc_insertion_point(class_scope:DawnMud.Zone)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::RepeatedPtrField< ::std::string> builders_;
  ::google::protobuf::int32 lifespan_;
  ::google::protobuf::int32 age_;
  ::google::protobuf::int32 bot_;
  ::google::protobuf::int32 top_;
  int reset_mode_;
  ::google::protobuf::int32 number_;
  ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone_ResetCommands > reset_com_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_dawnmud_2eproto();
  friend void protobuf_AssignDesc_dawnmud_2eproto();
  friend void protobuf_ShutdownFile_dawnmud_2eproto();

  void InitAsDefaultInstance();
  static Zone* default_instance_;
};
// -------------------------------------------------------------------

class ZoneList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DawnMud.ZoneList) */ {
 public:
  ZoneList();
  virtual ~ZoneList();

  ZoneList(const ZoneList& from);

  inline ZoneList& operator=(const ZoneList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZoneList& default_instance();

  void Swap(ZoneList* other);

  // implements Message ----------------------------------------------

  inline ZoneList* New() const { return New(NULL); }

  ZoneList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZoneList& from);
  void MergeFrom(const ZoneList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ZoneList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .DawnMud.Zone zone = 1;
  int zone_size() const;
  void clear_zone();
  static const int kZoneFieldNumber = 1;
  const ::DawnMud::Zone& zone(int index) const;
  ::DawnMud::Zone* mutable_zone(int index);
  ::DawnMud::Zone* add_zone();
  ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone >*
      mutable_zone();
  const ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone >&
      zone() const;

  // @@protoc_insertion_point(class_scope:DawnMud.ZoneList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone > zone_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_dawnmud_2eproto();
  friend void protobuf_AssignDesc_dawnmud_2eproto();
  friend void protobuf_ShutdownFile_dawnmud_2eproto();

  void InitAsDefaultInstance();
  static ZoneList* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Zone_ResetCommands

// optional .DawnMud.Zone.ResetCommands.Commands command = 1;
inline void Zone_ResetCommands::clear_command() {
  command_ = 0;
}
inline ::DawnMud::Zone_ResetCommands_Commands Zone_ResetCommands::command() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.ResetCommands.command)
  return static_cast< ::DawnMud::Zone_ResetCommands_Commands >(command_);
}
inline void Zone_ResetCommands::set_command(::DawnMud::Zone_ResetCommands_Commands value) {
  
  command_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.ResetCommands.command)
}

// optional bool if_flag = 2;
inline void Zone_ResetCommands::clear_if_flag() {
  if_flag_ = false;
}
inline bool Zone_ResetCommands::if_flag() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.ResetCommands.if_flag)
  return if_flag_;
}
inline void Zone_ResetCommands::set_if_flag(bool value) {
  
  if_flag_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.ResetCommands.if_flag)
}

// optional sint32 arg1 = 3;
inline void Zone_ResetCommands::clear_arg1() {
  arg1_ = 0;
}
inline ::google::protobuf::int32 Zone_ResetCommands::arg1() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.ResetCommands.arg1)
  return arg1_;
}
inline void Zone_ResetCommands::set_arg1(::google::protobuf::int32 value) {
  
  arg1_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.ResetCommands.arg1)
}

// optional sint32 arg2 = 4;
inline void Zone_ResetCommands::clear_arg2() {
  arg2_ = 0;
}
inline ::google::protobuf::int32 Zone_ResetCommands::arg2() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.ResetCommands.arg2)
  return arg2_;
}
inline void Zone_ResetCommands::set_arg2(::google::protobuf::int32 value) {
  
  arg2_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.ResetCommands.arg2)
}

// optional sint32 arg3 = 5;
inline void Zone_ResetCommands::clear_arg3() {
  arg3_ = 0;
}
inline ::google::protobuf::int32 Zone_ResetCommands::arg3() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.ResetCommands.arg3)
  return arg3_;
}
inline void Zone_ResetCommands::set_arg3(::google::protobuf::int32 value) {
  
  arg3_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.ResetCommands.arg3)
}

// optional sint32 line = 6;
inline void Zone_ResetCommands::clear_line() {
  line_ = 0;
}
inline ::google::protobuf::int32 Zone_ResetCommands::line() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.ResetCommands.line)
  return line_;
}
inline void Zone_ResetCommands::set_line(::google::protobuf::int32 value) {
  
  line_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.ResetCommands.line)
}

// -------------------------------------------------------------------

// Zone

// optional string name = 1;
inline void Zone::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Zone::name() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Zone::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DawnMud.Zone.name)
}
inline void Zone::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DawnMud.Zone.name)
}
inline void Zone::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DawnMud.Zone.name)
}
inline ::std::string* Zone::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:DawnMud.Zone.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Zone::release_name() {
  // @@protoc_insertion_point(field_release:DawnMud.Zone.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Zone::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DawnMud.Zone.name)
}

// repeated string builders = 2;
inline int Zone::builders_size() const {
  return builders_.size();
}
inline void Zone::clear_builders() {
  builders_.Clear();
}
inline const ::std::string& Zone::builders(int index) const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.builders)
  return builders_.Get(index);
}
inline ::std::string* Zone::mutable_builders(int index) {
  // @@protoc_insertion_point(field_mutable:DawnMud.Zone.builders)
  return builders_.Mutable(index);
}
inline void Zone::set_builders(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:DawnMud.Zone.builders)
  builders_.Mutable(index)->assign(value);
}
inline void Zone::set_builders(int index, const char* value) {
  builders_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:DawnMud.Zone.builders)
}
inline void Zone::set_builders(int index, const char* value, size_t size) {
  builders_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:DawnMud.Zone.builders)
}
inline ::std::string* Zone::add_builders() {
  // @@protoc_insertion_point(field_add_mutable:DawnMud.Zone.builders)
  return builders_.Add();
}
inline void Zone::add_builders(const ::std::string& value) {
  builders_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:DawnMud.Zone.builders)
}
inline void Zone::add_builders(const char* value) {
  builders_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:DawnMud.Zone.builders)
}
inline void Zone::add_builders(const char* value, size_t size) {
  builders_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:DawnMud.Zone.builders)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Zone::builders() const {
  // @@protoc_insertion_point(field_list:DawnMud.Zone.builders)
  return builders_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Zone::mutable_builders() {
  // @@protoc_insertion_point(field_mutable_list:DawnMud.Zone.builders)
  return &builders_;
}

// optional sint32 lifespan = 3;
inline void Zone::clear_lifespan() {
  lifespan_ = 0;
}
inline ::google::protobuf::int32 Zone::lifespan() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.lifespan)
  return lifespan_;
}
inline void Zone::set_lifespan(::google::protobuf::int32 value) {
  
  lifespan_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.lifespan)
}

// optional sint32 age = 4;
inline void Zone::clear_age() {
  age_ = 0;
}
inline ::google::protobuf::int32 Zone::age() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.age)
  return age_;
}
inline void Zone::set_age(::google::protobuf::int32 value) {
  
  age_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.age)
}

// optional sint32 bot = 5;
inline void Zone::clear_bot() {
  bot_ = 0;
}
inline ::google::protobuf::int32 Zone::bot() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.bot)
  return bot_;
}
inline void Zone::set_bot(::google::protobuf::int32 value) {
  
  bot_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.bot)
}

// optional sint32 top = 6;
inline void Zone::clear_top() {
  top_ = 0;
}
inline ::google::protobuf::int32 Zone::top() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.top)
  return top_;
}
inline void Zone::set_top(::google::protobuf::int32 value) {
  
  top_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.top)
}

// optional .DawnMud.Zone.ResetMode reset_mode = 7;
inline void Zone::clear_reset_mode() {
  reset_mode_ = 0;
}
inline ::DawnMud::Zone_ResetMode Zone::reset_mode() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.reset_mode)
  return static_cast< ::DawnMud::Zone_ResetMode >(reset_mode_);
}
inline void Zone::set_reset_mode(::DawnMud::Zone_ResetMode value) {
  
  reset_mode_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.reset_mode)
}

// optional sint32 number = 8;
inline void Zone::clear_number() {
  number_ = 0;
}
inline ::google::protobuf::int32 Zone::number() const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.number)
  return number_;
}
inline void Zone::set_number(::google::protobuf::int32 value) {
  
  number_ = value;
  // @@protoc_insertion_point(field_set:DawnMud.Zone.number)
}

// repeated .DawnMud.Zone.ResetCommands reset_com = 9;
inline int Zone::reset_com_size() const {
  return reset_com_.size();
}
inline void Zone::clear_reset_com() {
  reset_com_.Clear();
}
inline const ::DawnMud::Zone_ResetCommands& Zone::reset_com(int index) const {
  // @@protoc_insertion_point(field_get:DawnMud.Zone.reset_com)
  return reset_com_.Get(index);
}
inline ::DawnMud::Zone_ResetCommands* Zone::mutable_reset_com(int index) {
  // @@protoc_insertion_point(field_mutable:DawnMud.Zone.reset_com)
  return reset_com_.Mutable(index);
}
inline ::DawnMud::Zone_ResetCommands* Zone::add_reset_com() {
  // @@protoc_insertion_point(field_add:DawnMud.Zone.reset_com)
  return reset_com_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone_ResetCommands >*
Zone::mutable_reset_com() {
  // @@protoc_insertion_point(field_mutable_list:DawnMud.Zone.reset_com)
  return &reset_com_;
}
inline const ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone_ResetCommands >&
Zone::reset_com() const {
  // @@protoc_insertion_point(field_list:DawnMud.Zone.reset_com)
  return reset_com_;
}

// -------------------------------------------------------------------

// ZoneList

// repeated .DawnMud.Zone zone = 1;
inline int ZoneList::zone_size() const {
  return zone_.size();
}
inline void ZoneList::clear_zone() {
  zone_.Clear();
}
inline const ::DawnMud::Zone& ZoneList::zone(int index) const {
  // @@protoc_insertion_point(field_get:DawnMud.ZoneList.zone)
  return zone_.Get(index);
}
inline ::DawnMud::Zone* ZoneList::mutable_zone(int index) {
  // @@protoc_insertion_point(field_mutable:DawnMud.ZoneList.zone)
  return zone_.Mutable(index);
}
inline ::DawnMud::Zone* ZoneList::add_zone() {
  // @@protoc_insertion_point(field_add:DawnMud.ZoneList.zone)
  return zone_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone >*
ZoneList::mutable_zone() {
  // @@protoc_insertion_point(field_mutable_list:DawnMud.ZoneList.zone)
  return &zone_;
}
inline const ::google::protobuf::RepeatedPtrField< ::DawnMud::Zone >&
ZoneList::zone() const {
  // @@protoc_insertion_point(field_list:DawnMud.ZoneList.zone)
  return zone_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DawnMud

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::DawnMud::Zone_ResetCommands_Commands> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DawnMud::Zone_ResetCommands_Commands>() {
  return ::DawnMud::Zone_ResetCommands_Commands_descriptor();
}
template <> struct is_proto_enum< ::DawnMud::Zone_ResetMode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DawnMud::Zone_ResetMode>() {
  return ::DawnMud::Zone_ResetMode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dawnmud_2eproto__INCLUDED
